version: '3.5'
services:
  postgres:
    image: vukfx/postgresql
    container_name: postgresql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - type: volume
        source: rssdatapgl
        target: /var/lib/postgresql/data
    command: postgres -c log_statement=all
    logging:
      driver: local
    networks:
      - mynetwork
  nestjs_prisma:
    image: vukfx/nestjs-prisma
    container_name: nestjs-prisma
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - postgres
    networks:
      - mynetwork
volumes:
  rssdatapgl:
networks:
  mynetwork:
